version: '2'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mydata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD

volumes:
  mydata: