CREATE TABLE subscriber (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL DEFAULT '',
    last_name VARCHAR(255) NOT NULL DEFAULT '',
    number VARCHAR(15) NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    status ENUM ('ACTIVE', 'BLOCKED'),
    pin VARCHAR(60) NOT NULL
);