CREATE TABLE subscriber (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL DEFAULT '',
    last_name VARCHAR(255) NOT NULL DEFAULT '',
    msisdn BIGINT UNSIGNED NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    status ENUM ('ACTIVE', 'BLOCKED'),
    pin CHAR(60) NOT NULL
);